GAST-15 Creating header
RafaCardinali/gastronomy-lp-demo pull request #5
Opened 2024-01-10 15:09 UTC by RafaCardinali

2024-01-11 02:14 UTC, RaafaW requested changes

2024-01-11 02:14 UTC, RaafaW commented on index.html
Verifique a possibilidade de componentizar o html também. A estrutura de pastas ficaria:

raiz > components + índex.html + styles.css > pasta do compontente > pasta css + pasta html > arquivo css + arquivo html

Importando os css no styles.css e os html no index.html

2024-01-11 02:14 UTC, RaafaW commented on js/script.js
Componentizar os js também, na mesma estrutura que comentei do html e css. Criar uma pasta para cada componente que for necessário

2024-01-11 02:14 UTC, RaafaW commented on js/script.js
> +const secondColor = rootStyle.getPropertyValue('--second-color').trim();
Ajustar a nomenclatura para secondaryColor em todos os lugares que estiverem errados

2024-01-11 02:14 UTC, RaafaW commented on js/script.js
> +const menu = document.querySelector('.hamburguer__content');
Melhor nomenclatura seria menuItems ou menuContent

2024-01-11 02:14 UTC, RaafaW commented on js/script.js
> +        menu.style.display = 'none';
Modularizar a manipulação dos elementos em funções menores

2024-01-11 02:14 UTC, RaafaW commented on js/script.js
> +        menu.style.display = 'block';
Modularizar a manipulação dos elementos em funções menores

2024-01-11 02:14 UTC, RaafaW commented on js/script.js
> +        const icon = parentLink.querySelector('.material-symbols-outlined');
Melhorar nomenclatura

2024-01-11 02:14 UTC, RaafaW commented on js/script.js
> +                submenu.style.display = 'none';
Modularizar a manipulação dos elementos em funções menores

2024-01-11 02:14 UTC, RaafaW commented on js/script.js
> +                submenu.style.display = 'block';
Modularizar a manipulação dos elementos em funções menores

2024-01-11 02:14 UTC, RaafaW commented on css/hamburguer.css
> +
Linha em branco

2024-01-11 02:14 UTC, RaafaW commented on css/hamburguer.css
> +    /* Estilos para os submenus */
Remover comentários

2024-01-11 02:14 UTC, RaafaW commented on css/hamburguer.css
> +
Linha em branco

2024-01-12 14:23 UTC, RafaCardinali commented on js/script.js
conforme combinado faremos isso em uma nova task

2024-01-12 14:23 UTC, RafaCardinali commented on index.html
conforme combinado faremos isso em uma nova task

2024-01-15 21:28 UTC, RaafaW approved these changes

2024-01-15 21:28 UTC, RaafaW commented on css/topbar.css
> +
linha em branco

2024-01-15 21:28 UTC, RaafaW commented on css/topbar.css
> +
linha em branco

2024-01-15 21:28 UTC, RaafaW commented on css/topbar.css
> +
espaço em branco

2024-01-15 21:28 UTC, merged